### ISSUE TITLE
Initial Thoughts / Feedback / Bugs

### ISSUE THREAD

**Issue by maia-fw** [DrOgres/electric-state#19]
Hey there, here are my initial thoughts after downloading this new module. I made a screen-recording as I thought that would be faster/more efficient and that way you can see me walkthrough this all for the first time and everything I encounter. Found a couple bugs as well. 

[https://www.loom.com/share/0489297081554065b366ff8558f1e487?sid=a4d8b09d-97c2-4a5e-be9e-cea5f56fdd03](https://www.loom.com/share/0489297081554065b366ff8558f1e487?sid=a4d8b09d-97c2-4a5e-be9e-cea5f56fdd03)

**Comment by maia-fw** [comment]
I'm also a UI/UX designer, so if you need someone to help out with those designs, lemme know :)

**Comment by maia-fw** [comment]
## Written version
### Feedback + Suggestions
- Archetypes could be selected via a drop-down menu for easier selection.
- Flaw text box could be longer, similar to the description text box, to accommodate more detailed information.
- The "dream" field could also use a larger paragraph-style text box for better usability.
- Suggested that the default value for health and hope should be five instead of zero, with both sides pre-filled to avoid confusion.
- Consider adding plus and minus buttons (arrows) next to health, hope, or bliss for easier value adjustments.

### Bugs
- Default value for health and hope starts at zero, which can be confusing for users; needs correction or adjustment.
- The editing field for "Notes" did not seem to be working.
- Rolls were not working correctly:
  - Supposed to roll the number of dice equal to the value set in the stats box, but only rolled one die instead.
  - Equipment rolls were not working at all, no dice were rolled.

**Comment by DrOgres** [comment]
dice rolling is fixed

**Comment by DrOgres** [comment]
notes editor size was being set too small by foundry should  be fixed now

**Comment by maia-fw** [comment]
> dice rolling is fixed

- Still only rolling one die
- Not rolling at all for equipment or weapons
- Still unable to edit notes

[https://www.loom.com/share/cbe7129256654e1c920b5da8482f2691?sid=10cc2e3f-bcc5-4567-b538-c80f4ec5c574](https://www.loom.com/share/cbe7129256654e1c920b5da8482f2691?sid=10cc2e3f-bcc5-4567-b538-c80f4ec5c574)

**Comment by maia-fw** [comment]
### ES 0.4.0 Bugs
[https://www.loom.com/share/89d849c72d134694886535a81a5375b4?sid=c4c2eb5c-d2be-40aa-a86b-8225c154740f](https://www.loom.com/share/89d849c72d134694886535a81a5375b4?sid=c4c2eb5c-d2be-40aa-a86b-8225c154740f)

- [ ] Still only rolling one die
- [ ] Not rolling at all for equipment or weapons
- [ ] Still unable to edit notes
- [ ] Keyboard arrows do not work changing Hope amount

**Comment by maia-fw** [comment]
### ES 0.4.0 Bug - Not showing successes - 8 October 2024
Testing out rolling using the dice roller under chat and its not showing any of the successes rolled. 

[https://www.loom.com/share/c68474b3b71c42cc8770e6f52809c269?sid=c3932d4e-1103-4570-9c1a-7a83b36d5a8c](https://www.loom.com/share/c68474b3b71c42cc8770e6f52809c269?sid=c3932d4e-1103-4570-9c1a-7a83b36d5a8c)

**Comment by maia-fw** [comment]
### ES 0.4.0 Bug - Not showing failures after Pushing - 8 October 2024

[https://www.loom.com/share/e90dde95a10d461f89b1e0a16c83a5de?sid=0ec04c3c-5032-4652-a31b-ee460c2ddccf](https://www.loom.com/share/e90dde95a10d461f89b1e0a16c83a5de?sid=0ec04c3c-5032-4652-a31b-ee460c2ddccf)

**Comment by DrOgres** [comment]
> ### ES 0.4.0 Bug - Not showing failures after Pushing - 8 October 2024
> 
> https://www.loom.com/share/e90dde95a10d461f89b1e0a16c83a5de?sid=0ec04c3c-5032-4652-a31b-ee460c2ddccf

A future feature will be applying 1's on pushed dice as loss of hope and gear damage automatically. this is planned.

**Comment by Nyogtha68** [comment]
RE: 0.7.0
Hope adjustment on pushed rolls is being applied, but adjustments to gear dice bonus of items doesn't seem to work.

**Comment by DrOgres** [comment]
> RE: 0.7.0 Hope adjustment on pushed rolls is being applied, but adjustments to gear dice bonus of items doesn't seem to work.

If you are rolling from a token (in a scene or the like) and do not have the Link Actor Data checked it wont.  this is because of the way items update.  i will be updating actors have this set as the default in a future update

![image](https://github.com/user-attachments/assets/a55e830e-6e90-4ad8-91eb-fe86cc6e2726)

can you check this and see if it still doesn't work when this is checked?

**Comment by Nyogtha68** [comment]
Still the same.  
![image](https://github.com/user-attachments/assets/605e663d-8e24-427d-9ef4-89c4b7cca8e4)


________________________________

**Comment by DrOgres** [comment]
oh Weapons!  no those aren't in yet, it's a different bit of code.  Just Gear items are in at this point

**Comment by Nyogtha68** [comment]
Ohh, sorry will test again. Thanks though. And thank you for the making the mod.  Going on your previous work,I take it this is going to be an official release when finished?

**Comment by Nyogtha68** [comment]
Yep works. 👍 
![image](https://github.com/user-attachments/assets/2326afd4-d823-4e94-b154-5c147796205d)

**Comment by DrOgres** [comment]
weapons will be in the next update just testing it now

as of right now there is no contract with Free League, so I don't know they have plans for an official release (i think there may be some contractual issues on this but am not sure.)

**Comment by Angrymog** [comment]
Noticed this after the recent update.

If, as the GM,  you have two or more player character sheets open, you have to close them in exactly the same order that you opened them in, or the following fields : Dream, Flaw, Goal, and Threat are overwritten with the values from the first sheet that you opened.

Note that the sheets aren't assigned to players because I'm using this as a solo game.

**Comment by DrOgres** [comment]
> Noticed this after the recent update.
> 
> If, as the GM, you have two or more player character sheets open, you have to close them in exactly the same order that you opened them in, or the following fields : Dream, Flaw, Goal, and Threat are overwritten with the values from the first sheet that you opened.
> 
> Note that the sheets aren't assigned to players because I'm using this as a solo game.

fixed in v0.15.0

**Comment by Nyogtha68** [comment]
Death Roll button reports can't be used if health is above zero, but when zero it doesn't do anything.

**Comment by DrOgres** [comment]
> Death Roll button reports can't be used if health is above zero, but when zero it doesn't do anything.

fixed in 0.16.0

**Comment by Angrymog** [comment]
When using the Neurocaster, only Finding information has the adds correctly calculated.  The other actions use the 'Real World Penalty' value in place of the stat.

When doing a Stat roll with the NC equipped, the RL penalty isn't applied automatically.  (I don't know if you plan for it to do so, so this might be working as intended)

**Comment by DrOgres** [comment]
> When doing a Stat roll with the NC equipped, the RL penalty isn't applied automatically. (I don't know if you plan for it to do so, so this might be working as intended)

this will be in an upcoming release

**Comment by DrOgres** [comment]
> When using the Neurocaster, only Finding information has the adds correctly calculated. The other actions use the 'Real World Penalty' value in place of the stat.
> 
fixed in 0.17.0

**Comment by Nyogtha68** [comment]
Names dissapear from Tensions when edited by player and drop down menu not functioning.
![image](https://github.com/user-attachments/assets/19e86053-b553-476c-a0c3-255c9c4c8faa)

**Comment by DrOgres** [comment]
> Names dissapear from Tensions when edited by player and drop down menu not functioning. ![image](https://private-user-images.githubusercontent.com/88248539/380643176-19e86053-b553-476c-a0c3-255c9c4c8faa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxMDczNTIsIm5iZiI6MTczMDEwNzA1MiwicGF0aCI6Ii84ODI0ODUzOS8zODA2NDMxNzYtMTllODYwNTMtYjU1My00NzZjLWEwYzMtMjU1YzljNGM4ZmFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI4VDA5MTczMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxZGI5MmNlODYzYzA0MDg0YjYzMDhhYTEzNDRmYzc2MWRmZTMyNjQ4NzI0ODM5YTk4MDVmNzZhMThiM2ZkNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vX3PTVrKe8VW2LZqMHURFA04IvUIBVI2S--h77BnK6I)

the player must have Limited permissions to the characters they can use for tension, this is necessary to prevent them from seeing a list of all actors including NPC,s Robots and the like. 

can you change permissions for me and verify that this fixes the issue?

**Comment by Nyogtha68** [comment]
That seems to fix it, will keep an eye on it.  Although, if the player opens another player's character sheet it won't let them close it again, saying they lack permission to do so.
![image](https://github.com/user-attachments/assets/578e7f5c-f0a7-4e97-abc2-0bdb04fda352)

**Comment by Nyogtha68** [comment]
Hull vehicle bonus applied to Armour instead of Hull.
![image](https://github.com/user-attachments/assets/0ab3a151-ef52-4e48-a515-594f8fa11e08)

**Comment by DrOgres** [comment]
> Hull vehicle bonus applied to Armour instead of Hull. ![image](https://private-user-images.githubusercontent.com/88248539/382363815-0ab3a151-ef52-4e48-a515-594f8fa11e08.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0ODczODcsIm5iZiI6MTczMDQ4NzA4NywicGF0aCI6Ii84ODI0ODUzOS8zODIzNjM4MTUtMGFiM2ExNTEtZWY1Mi00ZTQ4LWE1MTUtNTk0ZjhmYTExZTA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDE4NTEyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2OTg0NzhiNjY3ODYxOWYxYzY2YTExYTdiOWExYzgxYWIxNGYyZTUxYzJjYWM4ZmM4NmY4Zjk5MDkxYjdmZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.DsKCB2_16D4Z8WQbk9lFZj4R1XaujWj4TFPSOdf9tgw)

fixed in 0.20.0
